name: Deploy to Amazon 

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-central-1


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

#    - name: Configure AWS credentials
 #     uses: aws-actions/configure-aws-credentials@v1
  #    with:
   #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
     #   aws-region: ${{ env.AWS_REGION }}
      # Setup key
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.AWS_FRANKFURT }}" > "$HOME/.ssh/AWS_FRANKFURT"
    - run: chmod 600 "$HOME/.ssh/AWS_FRANKFURT"

      # Deploy 
    - run: rsync -Oe "ssh -i $HOME/.ssh/AWS_FRANKFURT -o StrictHostKeyChecking=no" --archive --compress --delete . bersnev@18.185.149.57:/var/www/html/
